<?php

namespace ChenJiaJing\WeWork;

use Illuminate\Support\ServiceProvider;

class WeWorkServiceProvider extends ServiceProvider
{

    public function boot()
    {

    }

    public function  register()
    {
       // parent::register(); // TODO: Change the autogenerated stub
        $this->app->singleton('wework', function () {
            return new WeWork();
        });
    }

}
